eureka.client.enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server.port: 7000
server.forward-headers-strategy: NATIVE

spring.application.name: cfg-examples

spring.datasource.url: mongodb://my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local:27017,my-release-mongodb-1.my-release-mongodb-headless.default.svc.cluster.local:27017,my-release-mongodb-2.my-release-mongodb-headless.default.svc.cluster.local:27017/coursework?replicaSet=replicaset
#spring.datasource.url: mongodb://mongo-0:27017/coursework?replicaSet=replicaset
spring.datasource.username: root
spring.datasource.password: root

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
