FROM postgres:16.2-alpine3.19

ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=cfg_repository
ENV LANG=ru_RU.utf8

COPY microservices/cfg-examples/src/main/resources/sql-cfg-repository/* /docker-entrypoint-initdb.d/
