FROM openjdk:17-jdk-alpine

ARG JAR_FILE=microservices/authentication-server/build/libs/authentication-server-1.0.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /app.jar"]