FROM golang:1.24-alpine3.21 AS builder
WORKDIR /app
ARG PROJ_DIR=authentication-service
COPY ../../$PROJ_DIR/go.mod ../../$PROJ_DIR/go.sum ./
RUN go mod download
COPY ../../$PROJ_DIR ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64  go build -C ./cmd -o ../app

FROM alpine:3.21
WORKDIR /app
COPY --from=builder /app/app /app/.env ./
COPY ../../front-end/build ./static
RUN chmod 755 ./app
ENTRYPOINT ["/bin/sh", "-c", "./app"]
