FROM golang:1.24-alpine3.21
WORKDIR /app
COPY ../../file-server/go.mod ./
RUN go mod download
COPY ../../file-server ./
COPY ../../front-end/build ./static
RUN CGO_ENABLED=0 GOOS=linux go build -C ./cmd -o ../app
ENTRYPOINT ["/bin/sh", "-c", "./app"]