apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000,http://localhost:80"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: file-server-svc
                port:
                  number: 8080
    - http:
        paths:
          - path: /()(processor.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cfg-processor-svc
                port:
                  number: 8080
    - http:
        paths:
          - path: /()auth/(login)
            pathType: ImplementationSpecific
            backend:
              service:
                name: authentication-service-svc
                port:
                  number: 8080
    - http:
        paths:
          - path: /()keycloak(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: keycloak-svc
                port:
                  number: 8080
    - http:
        paths:
          - path: /()(examples.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cfg-examples-svc
                port:
                  number: 8080